# 阻止Helm Chart自己创建命名空间
# 我们将这个责任交给Argo CD的 syncOptions
namespace:
  create: false

# 在这里覆盖默认的Helm Chart值
grafana:
  service:
    type: NodePort

prometheus:
  service:
    type: NodePort
    
alertmanager:
  service:
    type: NodePort
