apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-milvus-etcd
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-milvus-minio
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-milvus-standalone
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
